package controller.implementations;
// Generated 10-Mar-2019 19:07:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersHaveUsersId generated by hbm2java
 */
@Embeddable
public class UsersHaveUsersId  implements java.io.Serializable {


     private String phoneA;
     private String phoneB;

    public UsersHaveUsersId() {
    }

    public UsersHaveUsersId(String phoneA, String phoneB) {
       this.phoneA = phoneA;
       this.phoneB = phoneB;
    }
   


    @Column(name="phone_a", nullable=false, length=20)
    public String getPhoneA() {
        return this.phoneA;
    }
    
    public void setPhoneA(String phoneA) {
        this.phoneA = phoneA;
    }


    @Column(name="phone_b", nullable=false, length=20)
    public String getPhoneB() {
        return this.phoneB;
    }
    
    public void setPhoneB(String phoneB) {
        this.phoneB = phoneB;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersHaveUsersId) ) return false;
		 UsersHaveUsersId castOther = ( UsersHaveUsersId ) other; 
         
		 return ( (this.getPhoneA()==castOther.getPhoneA()) || ( this.getPhoneA()!=null && castOther.getPhoneA()!=null && this.getPhoneA().equals(castOther.getPhoneA()) ) )
 && ( (this.getPhoneB()==castOther.getPhoneB()) || ( this.getPhoneB()!=null && castOther.getPhoneB()!=null && this.getPhoneB().equals(castOther.getPhoneB()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPhoneA() == null ? 0 : this.getPhoneA().hashCode() );
         result = 37 * result + ( getPhoneB() == null ? 0 : this.getPhoneB().hashCode() );
         return result;
   }   


}


